version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - benchmark
  benchmark-ws:
    build:
        context: .
        dockerfile: ./Dockerfile
    networks:
      - benchmark
    ports:
      - "1323:1323"
networks:
  benchmark:
    driver: bridge